apiVersion: v1
kind: ConfigMap

metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::485323199507:role/raphael-marco-tier-3-dev-eks-node-group-default
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::485323199507:role/raphael-marco-tier-3-dev-express-minapp-project
      username: build
      groups:
        - system:masters
